### ISSUE TITLE
Implement DeriveCredential for selective disclosure

### ISSUE THREAD

**Issue by youngjoon-lee** [medibloc/vc-sdk#5]
https://github.com/hyperledger/aries-framework-go/pull/2776
My contribution to hyperleder/aries-framework-go has not been merged so far. That contribution fixes a bug in 32-bit architecture.

So, until then, let's implement DeriveCredential using the current version of aires-framework-go.

**Comment by troyronda** [comment]
@youngjoon-lee AFG has now been updated.

**Comment by youngjoon-lee** [comment]
@troyronda Thank you so much!

**Comment by youngjoon-lee** [comment]
The [PR](chore: update to latest bbs12-381 module) in the aries-framework-go has been merged, but not released yet as v0.1.7.

Because I've already implemented the DeriveCredential as https://github.com/medibloc/vc-sdk/pull/6, I will close this issue and open another issue just for bumping the version of aries-framework-go,
